name: Building Images with a CI/CD

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t house-price-pred .

      - name: Push Docker image
        run: |
          docker tag house-price-pred ${{ secrets.DOCKER_USERNAME }}/house-price-pred:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/house-price-pred:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/house-price-pred:latest
            docker stop house-price-pred || true
            docker rm house-price-pred || true
            docker run -d --name house-price-pred -p 8080:8000 ${{ secrets.DOCKER_USERNAME }}/house-price-pred:latest
